config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/admin/autocomplete_tags',
      to: 'application#autocomplete_tags',
      as: 'autocomplete_tags'
  
  put '/admin/order_images_in_tag',
      to: 'application#order_images_in_tag',
      as: 'order_images_in_tag'

  get '/albums', to: 'home#index', defaults: { disable_hero: true }
  get '/info', to: 'home#about'
  get '/tagged/:tag_name', as: :tagged, to: 'home#tagged'
  get '/:id', as: :album, to: 'home#album'
  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  scope :published, -> { where(published: true).order('position asc') }

  attr_accessor :delete_cover_image
  before_validation { self.file.clear if self.delete_cover_image == '1' }

  # Background Color
  attr_accessor :background_color
  has_settings :base
  before_save -> {
    settings(:base).background_color = background_color
  }

  validates :name, presence: true, uniqueness: true
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  acts_as_taggable
  acts_as_list
  has_many :images, -> { order(position: :asc) }, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  def visible_images
    self.images.select { |i| i.visible? }
  end

  has_attached_file :file, {
    styles: {
      thumb: {
        geometry: '200x',
        processor_options: {
          compression: {
            png: false,
            jpeg: '-copy none -optimize -progressive'
          }
        }
      },
      medium: {
        geometry: '800x',
        processor_options: {
          compression: {
            png: false,
            jpeg: '-copy none -optimize -progressive'
          }
        }
      },
      full: {
        geometry: '1200x',
        processor_options: {
          compression: {
            png: false,
            jpeg: '-copy none -optimize -progressive'
          }
        }
      },
    },
    processors: [:thumbnail, :compression],
    default_url: "/images/missing.jpg",
    convert_options: {
      thumb: '-quality 80',
      medium: '-quality 45',
      full: '-quality 80'
    }
  }

  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
  validates :file, dimensions: { width: 1200 }

  has_one :page

  def cover_image
    if file.present? || images.empty?
      file
    else
      images.first.file
    end
  end

end

app/models/child_image.rb
class ChildImage < Image
  belongs_to :image
  delegate :album, to: :image
end

app/models/dimensions_validator.rb
class DimensionsValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    if record.send("#{attribute}?".to_sym) && value.queued_for_write[:original].present?
      dimensions = Paperclip::Geometry.from_file(value.queued_for_write[:original].path)
      width = options[:width]

      record.errors[attribute] << "Width must be at least #{width}px" unless dimensions.width >= width
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  scope :visible, -> {
    where(visible: true)
  }

  default_scope {
    order('position asc')
  }

  has_attached_file :file, {
    styles: {
      thumb: {
        geometry: '200x',
        processor_options: {
          compression: {
            png: false,
            jpeg: '-copy none -optimize -progressive'
          }
        }
      },
      medium: {
        geometry: '800x',
        processor_options: {
          compression: {
            png: false,
            jpeg: '-copy none -optimize -progressive'
          }
        }
      },
      full: {
        geometry: '1200x',
        processor_options: {
          compression: {
            png: false,
            jpeg: '-copy none -optimize -progressive'
          }
        }
      },
    },
    processors: [:thumbnail, :compression],
    default_url: "/images/missing.jpg",
    convert_options: {
      thumb: '-quality 80',
      medium: '-quality 80',
      full: '-quality 80'
    }
  }

  validates_attachment_content_type :file, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :file
  validates :file, dimensions: { width: 1200 }

  belongs_to :album, counter_cache: true
  has_one :child_image, dependent: :destroy
  acts_as_list scope: :album, top_of_list: '0'
  acts_as_taggable

  attr_accessor :child_image_file
  attr_accessor :child_image_tag_list
  attr_accessor :delete_child_image
  attr_accessor :child_image_visible

  def setup_child_image(file, delete='0', tag_list='', visible='0')
    visible = visible === '1'

    if delete == '1'
      self.child_image.destroy if self.child_image
    else
      if self.child_image
        self.child_image.update_attribute('file', file) if file
        self.child_image.update_attribute('visible', visible)
        self.child_image.tag_list = tag_list
        self.child_image.save
      else
        if file
          child_image = ChildImage.create({
            file: file,
            visible: visible,
            image: self
          })
          child_image.tag_list = tag_list
          child_image.save
        end
      end
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  # Background Color 
  attr_accessor :background_color
  has_settings :base
  before_save -> {
    settings(:base).background_color = background_color
  }

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  
  validates :name, presence: true, uniqueness: true

  belongs_to :album
end

app/models/tag_order.rb
class TagOrder < ActiveRecord::Base
  belongs_to :tag, class_name: 'ActsAsTaggableOn::Tag'
  serialize :image_ids, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def autocomplete_tags
    @tags = ActsAsTaggableOn::Tag.
      where("name LIKE ?", "#{params[:q]}%").
      order(:name)
    respond_to do |format|
      format.json { render :json => @tags.collect{|t| {:id => t.name, :name => t.name }}}
    end
  end

  def order_images_in_tag
    tag = ActsAsTaggableOn::Tag.find params[:tag_id]
    
    if tag
      tag_order = TagOrder.where(tag: tag).first_or_create do |tag_order|
        tag_order.tag = tag 
      end

      tag_order.image_ids = params[:order]
      tag_order.save
    end 

    respond_to do |format|
      format.json { render json: "success" }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    setup_filters

    @disable_hero = params[:disable_hero]

    @albums     = []
    @images     = []
    @photo_grid = false
    @tagged     = false

    @page              = Page.find('homepage')
    @slideshow_images = @page.album.images

    if params[:grid]
      @photo_grid = true
      if params[:tagged]
        @tagged = true
        @tag_name = params[:tagged]

        tag = ActsAsTaggableOn::Tag.find_by_name params[:tagged]
        if tag
          @images = tag.ordered_images.select { |i| i.visible? }
        else
          @images = Image.visible.tagged_with params[:tagged]
        end

      else
        @images = Image.visible
      end
    else
      @albums = Album.published.includes(:images)
    end
  end

  def about
    @page = Page.find 'about'
  end

  def tagged
    tag = ActsAsTaggableOn::Tag.find_by_name params[:tag_name]
    @tag_name = params[:tag_name]

    if tag
      @images = tag.ordered_images.select { |i| i.visible? }
    else
      @images = Image.tagged_with(params[:tag_name]).select { |i| i.visible? }
    end
  end

  def album
    @albums = Album.published
    @album = Album.includes(images: [:child_image]).find(params[:id])

    next_album_index = @albums.find_index(@album) + 1
    if next_album_index == @albums.count
      next_album_index = 0
    end

    previous_album_index = @albums.find_index(@album) - 1
    if previous_album_index == -1
      previous_album_index = @albums.count - 1
    end

    @next_album = @albums[next_album_index]
    @previous_album = @albums[previous_album_index]
  end

  private
  def setup_filters
    @tags = ActsAsTaggableOn::Tag.all.order('position asc')
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<%= render "shared/nav" %>
<div id='content' class="about" style="background-color: <%= @page.settings(:base).background_color %>">
  <div class='about-content vertical-center text-center'>
    <%= image_tag @page.album.images.first.file(:original) %>
    <h6><%= raw(@page.copy) %></h6>
  </div>
</div>

app/views/home/album.html.erb
<%= render "shared/nav" %>
<div id='content' class="album" style="background-color: <%= @album.settings(:base).background_color %>">

  <div class="swiper-container">
    <div class="swiper-wrapper">
      <% @album.visible_images.each do |image| %>
        <div class='swiper-slide' data-caption="<%= image.caption %>">
          <div class="image-cover left"></div>
          <div class="image-cover right"></div>

          <div class="slide-inner">
            <div class='background-image' style="background-image: url(<%= image.file.url(:full) %>)"></div>
            <% if image.child_image && image.child_image.visible? %>
              <div class='background-image' style="background-image: url(<%= image.child_image.file.url(:full) %>)"></div>
            <% end %>
          </div>

        </div>
      <% end %>
    </div>

    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  </div>

  <footer>
    <div class='page-count'>
      <span>1</span>
      / <%= @album.visible_images.count %>
    </div>
    <div id='caption'></div>

    <div class='album-navigation previous-album'>
      <%= link_to 'Previous Story', album_path(@previous_album.slug) %>
    </div>
    <div class='album-navigation next-album'>
      <%= link_to 'Next Story', album_path(@next_album.slug) %>
    </div>
  </footer>
</div>

app/views/home/index.html.erb
<%= render "shared/index_nav" %>

<div id='content' class="index" style="background-color: <%= @page.settings(:base).background_color %>">

  <% unless @disable_hero %>
    <% if (!@tagged && !@photo_grid) %>

      <div class="header-container">
        <% @slideshow_images.each_with_index do |image, index| %>
          <header class="header-slideshow transparent" style="background-image: url(<%= image.file(:full) %>)">
            <div class="header-content text-center vertical-center">
              <h1><%= @page.title %></h1>
              <h2><%= @page.copy %></h2>
            </div>
          </header>
        <% end %>

        <div class="down-arrow"></div>
      </div>
    <% end %>
  <% end %>

  <!-- No JS, for small only -->
  <div class="non-magic-grid <%= 'no-header' if (@photo_grid || @disable_hero) %>">
    <% @albums.each do |album| %>
      <%= link_to album_path(album), class: "grid-item" do %>
        <div class="overlay">
          <% if album.show_name_on_hover %>
            <div class='overlay-title text-center vertical-center'>
              <%= album.name %>
            </div>
          <% end %>
        </div>
        <%= image_tag album.cover_image.url(:medium), alt: album.name %>
      <% end %>
    <% end %>

    <% @images.each do |image| %>
      <%= link_to tagged_path(@tag_name, image: @images.find_index(image)), class: "grid-item" do %>
        <%= image_tag image.file.url(:medium) %>
      <% end %>
    <% end %>

  </div>

  <div class="magic-grid <%= 'no-header' if (@photo_grid || @disable_hero) %>">
    <% @albums.each do |album| %>
      <%= link_to album_path(album), class: "grid-item" do %>
        <div class="overlay">
          <% if album.show_name_on_hover %>
            <div class='overlay-title text-center vertical-center'>
              <%= album.name %>
            </div>
          <% end %>
        </div>
        <%= image_tag album.cover_image.url(:medium), alt: album.name %>
      <% end %>
    <% end %>

    <% @images.each do |image| %>
      <%= link_to tagged_path(@tag_name, image: @images.find_index(image)), class: "grid-item" do %>
        <%= image_tag image.file.url(:medium) %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/home/tagged.html.erb
<%= render "shared/tagged_nav" %>
<div id='content' class="album">

  <div class="swiper-container">
    <div class="swiper-wrapper">
      <% @images.each do |image| %>
        <div class='swiper-slide' data-caption="<%= image.caption %>">
          <div class="image-cover left"></div>
          <div class="image-cover right"></div>

          <div class="slide-inner">
            <div class='background-image' style="background-image: url(<%= image.file.url(:full) %>)"></div>
            <!--
            <% if image.child_image && image.child_image.visible? %>
              <div class='background-image' style="background-image: url(<%= image.child_image.file.url(:full) %>)"></div>
            <% end %>
            -->
          </div>

        </div>
      <% end %>
    </div>

    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
  </div>

  <footer>
    <div class='page-count'>
      <span>1</span>
      / <%= @images.count %>
    </div>
    <div id='caption'></div>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jaime Johnson</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="LA/NY based Photographer.">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, async: true %>
  <%= csrf_meta_tags %>

  <link rel="shortcut icon" href="<%= asset_path('favicon.png') %>" />

  <meta content="<%= asset_path('share.jpg') %>" property="og:image">
  <meta content="Jaime Johnson" property="og:title">
  <meta content="LA/NY based Photographer." property="og:description">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:creator" content="@jaimejohnsonny">
  <meta name="twitter:title" content="Jaime Johnson">
  <meta name="twitter:description" content="LA/NY based Photographer.">
  <meta name="twitter:image" content="<%= asset_path('share.jpg') %>">
</head>
<body>

  <%= yield %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-77368792-1', 'auto');
    ga('send', 'pageview');
  </script>

</body>
</html>

app/views/shared/_index_nav.html.erb
<nav class="index <%= 'scrolled down' if (@photo_grid || @disable_hero) %>
  <%= 'tagged' if @tagged %>">

  <% if @tags.length > 0 %>
    <div id='filters' class="clearfix">
      <div class="filter-work">WORK</div>
      <div class="tags-container">
        <% @tags.each do |tag| %>
          <div class="tag">
            <a href=".?tagged=<%= tag.name %>&grid=photos"><%=tag.name.upcase%></a>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= link_to root_path, class: 'logo' do %>
    <span id="logo">Jaime Johnson</span>
  <% end %>

  <% if !@tagged %>
    <div class="nav-icons">
      <a href="/">
        <div class="nav-icon__album-button <%= 'active' if !@photo_grid %>"></div>
      </a>
      <a href=".?grid=photos">
        <div class="nav-icon__image-button <%= 'active' if @photo_grid %>"></div>
      </a>
    </div>


  <% end %>

  <%= link_to "INFO", info_path, class: 'about-link' %>
</nav>

app/views/shared/_nav.html.erb
<nav class='index scrolled down album'>
  <%= link_to root_path, class: 'logo' do %>
    <span id="logo">Jaime Johnson</span>
  <% end %>

  <%= link_to albums_path, class: 'exit' do %>
    <%= image_tag('cross.svg') %>
  <% end %>
</nav>

app/views/shared/_tagged_nav.html.erb
<nav class='index scrolled down album'>
  <%= link_to root_path, class: 'logo' do %>
    <span id="logo">Jaime Johnson</span>
  <% end %>

  <%= link_to root_path(grid: 'photos', tagged: @tag_name), class: 'exit' do %>
    <%= image_tag('cross.svg') %>
  <% end %>
</nav>